extern crate gcc;

fn main() {
    gcc::Config::new()
        .target("arm-none-eabi")
        .compiler("arm-none-eabi-gcc")
        .pic(false)
        .flag("-DSTM32F103xB")
        .flag("-DUSE_HAL_DRIVER")
        .flag("-mcpu=cortex-m3")
        .flag("-mthumb")
        .flag("-Wall")
        .flag("-fdata-sections")
        .flag("-ffunction-sections")
        .flag("-Wa,-a,-ad")
        .flag("-g")
        .file("c/main.c")
        .file("c/stm32f1xx_hal.c")
        .file("c/stm32f1xx_hal_cortex.c")
        .file("c/stm32f1xx_hal_gpio.c")
        .file("c/stm32f1xx_hal_pcd.c")
        .file("c/stm32f1xx_hal_pcd_ex.c")
        .file("c/stm32f1xx_hal_rcc.c")
        .file("c/stm32f1xx_hal_rcc_ex.c")
        .file("c/stm32f1xx_it.c")
        .file("c/stm32f1xx_ll_usb.c")
        .file("c/system_stm32f1xx.c")
        .file("c/usbd_conf.c")
        .file("c/usbd_core.c")
        .file("c/usbd_ctlreq.c")
        .file("c/usbd_customhid.c")
        .file("c/usbd_custom_hid_if.c")
        .file("c/usbd_desc.c")
        .file("c/usb_device.c")
        .file("c/usbd_ioreq.c")
        .compile("usbcdc");
}
